name: xgcm
dependencies:
  - python=2.7
  - xarray
  - dask
  - numpy
  - future
  - pytest
  - numpydoc
  - sphinx
  - ipython
  - matplotlib
  - sphinx_rtd_theme
  - pip:
    - docrep
    - nbsphinx
