name: test_env_xgcm
channels:
  - conda-forge
dependencies:
  - codecov
  - dask
  - docrep<=0.2.7
  - numba
  - numpy
  - scipy
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - python
  - xarray
  - typing_extensions
