name: test_env_xgcm
dependencies:
  - python=3.6
  # - xarray # Now installed from master to catch breaking changes earlier.
  - dask
  - numpy >= 1.16
  - pytest
  - future
  - pip:
    - docrep
    - codecov
    - pytest-cov
    - black
